source 'https://rubygems.org'

gem 'json-ld', '>= 3.2.4'
gem 'json-ld-preloaded', '>= 3.3.0'
gem 'rdf-rdfa'
gem 'rdf-microdata', '>= 3.3.0'
gem 'rdf-reasoner'
gem 'rdf-turtle'
gem 'rspec'
gem 'rake'
gem 'nokogiri', '>= 1.15.6'
gem 'equivalent-xml'

group :debug do
  gem 'byebug'
end
