source 'https://rubygems.org'

gem 'json-ld'
gem 'json-ld-preloaded'
gem 'rdf-rdfa'
gem 'rdf-microdata', '>= 3.3.0'
gem 'rdf-reasoner'
gem 'rdf-turtle'
gem 'rspec'
gem 'rake'
gem 'nokogiri', '>= 1.16.5'
gem 'equivalent-xml'

group :debug do
  gem 'byebug'
end
